Repository CA22-game-creators/cookingbomb-apiserver, pull requests merged in 2021-06, with the labels that each got.

#41 fix: ID/Token生成・暗号化のエラーがない時にぬるぽになる
  util/crypto_manager.go
  util/id_generator.go
  util/token_generator.go
Labels: bugfix, レビュー待ち

#42 doc: grpcurl採用
  docs/development.md
Labels: doc, ship it!

#43 faet: 名前のバリデーション変更
  domain/model/user/name.go
  test/domain/model/user/name_test.go
  test/testdata/string/user/td.go
Labels: ship it!

#44 feat: apiにバリデーションを実装する
  go.mod
  go.sum
  presentation/account/controller.go
  test/presentation/account/controller_test.go
Labels: implement, レビュー待ち

#49 Dockerのネットワークを指定
  Makefile
  docker-compose.yml
  docs/development.md
Labels: ship it!

#51 feat: dockerを非root権限で実行する
  docker/app/local/Dockerfile
  docker/app/prod/Dockerfile
Labels: レビュー待ち
